version: '3.8'

services:
  singer_redis:
    image: redis:7.0-alpine
    container_name: "singer_redis"
    restart: on-failure

  singer_bot:
    container_name: "singer_bot"
    build: .
    image: singerbot:latest
    ports:
      - "8000:8000"
    depends_on:
      - singer_redis
      - singer_db
    env_file:
      - '.env'
    restart: on-failure

  singer_db:
    container_name: "singer_db"
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${DB_USER-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD-FGHJF4654@&$}
      - POSTGRES_DB=${DB_NAME-singer_music_bot}
      - POSTGRES_HOST_AUTH_METHOD=md5
    env_file: ".env"
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    expose:
      - 5432


volumes:
  db-data:
    name: db-data