"""add path to music model

Revision ID: dbf10fdecdf1
Revises: 989e04ff0894
Create Date: 2024-03-15 11:08:03.884284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbf10fdecdf1'
down_revision: Union[str, None] = '989e04ff0894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music', sa.Column('path', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('music', 'path')
    # ### end Alembic commands ###
