"""set price required to music model

Revision ID: f5cf29aa093f
Revises: 891c433759da
Create Date: 2024-04-26 09:03:09.761443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5cf29aa093f'
down_revision: Union[str, None] = '891c433759da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('music', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('music', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
